network_config:
  n_fft: 512
  hop_len: 256
  win_len: 512
  num_mics: 3

DDP:
  world_size: 2

optimizer:
  lr: 0.001

scheduler:
  kwargs:
    warmup_steps: 25000
    decay_until_step: 250000
    max_lr: 1e-3
    min_lr: 1e-6

  update_interval: step  # [step, epoch]

FFT:
  n_fft: 512
  hop_length: 256
  win_length: 512

loss:
  eps: 1e-12

train_dataset: 
  stage: 'train'
  prep_files: {
    data: '/path/to/prep_mix.hdf5',
    meta: '/path/to/prep_mix_meta.json'
  }
  n_channels: 3
  meta_frame_length: 48000
  dry_target: False
  disable_random: False

train_dataloader: 
  batch_size: 8
  num_workers: 4
  drop_last: True
  pin_memory: True

validation_dataset: 
  stage: 'val'
  prep_files: {
    data: '/path/to/prep_mix.hdf5',
    meta: '/path/to/prep_mix_meta.json'
  }
  n_channels: 3
  meta_frame_length: 48000
  dry_target: False
  disable_random: True

validation_dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: True

samplerate: 16000

trainer:
  epochs: 200
  save_checkpoint_interval: 1
  clip_grad_norm_value: 3.0
  exp_path: /data/ssd0/xiaobin.rong/study_se/DNS3/exp_gtcrn
  resume: False
  resume_datetime: 2024-12-31-14h28m
